# Generated by Django 3.2.3 on 2021-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_de_nasc', models.DateTimeField(blank=True, null=True)),
                ('endereco_rua', models.CharField(blank=True, max_length=300, null=True)),
                ('endereco_numero', models.IntegerField(blank=True, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_CEP', models.IntegerField(blank=True, null=True)),
                ('endereco_cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('DDD_telefone', models.IntegerField(blank=True, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=9, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': True,
            },
        ),
    ]
